"""add github pr fields to reviews

Revision ID: 6e95f8c318da
Revises: 7c005b8b3e88
Create Date: 2026-07-06 21:16:10.748271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e95f8c318da'
down_revision: Union[str, Sequence[str], None] = '7c005b8b3e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('pr_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'pr_url')
    # ### end Alembic commands ###
