"""add remaining github columns

Revision ID: bcb386d16b0b
Revises: 6e95f8c318da
Create Date: 2026-07-06 21:25:01.383536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb386d16b0b'
down_revision: Union[str, Sequence[str], None] = '6e95f8c318da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('source', sa.String(), nullable=True))
    op.execute("UPDATE reviews SET source = 'manual'")
    op.alter_column('reviews', 'source', nullable=False)
    op.add_column('reviews', sa.Column('repo_full_name', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('pr_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'pr_number')
    op.drop_column('reviews', 'repo_full_name')
    op.drop_column('reviews', 'source')
    # ### end Alembic commands ###
